### ISSUE TITLE
Have you optimized the image gen prompt? 

### ISSUE THREAD

**Issue by chenmosha** [utkrshm/StoryGPT#1]
Hi, utkrshm:

I've read the prompts for generating story and image, I want to know if you have optimized the image generation prompt for SD?

**Comment by utkrshm** [comment]
I don't exactly know what you mean, but the prompt for Stable Diffusion is generated by the LLM itself, and isn't separately generated.
I just format the LLM's response in such a way that it searches for some keywords to send to Stable Diffusion, and the rest of the prompt becomes the story.

In general, the LLM's responses are not optimized per se for Stable Diffusion, but for DALL-E. In the sense, that I ask the LLM to generate a image prompt for DALL-E not Stable Diffusion (it doesn't know what Stable Diffusion is).
